name: Publish toxbox

on:
  push:
    branches: ['main']
  workflow_dispatch:

jobs:
  publish:
    permissions:
      packages: write

    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ github.token }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build and publish image
        run: ./publish
